solution:
  application:
    fipewatcher:
      name: fipewatcher
      namespace: frontend
      image_name: fipewatcher
      image_tag: 1.2.0
      registryUrl: docker-registry:5000
      service:
        replicas: 1
    fipewatcher-backend:
      name: fipewatcher-backend
      namespace: backend
      image_name: fipewatcher-backend
      image_tag: 1.1.0
      registryUrl: docker-registry:5000
      service:
        replicas: 1

  devops:
    jenkins:
      name: jenkins
      namespace: jenkins
      repourl: https://charts.jenkins.io
      chart_ref: jenkins
      chart_version: "4.3.9"
      service: 
        replicas: 1
    docker_registry:
      name: docker-registry
      namespace: docker-registry
      repourl: https://helm.twun.io
      chart_ref: docker-registry
      service: 
        replicas: 1


